### ISSUE TITLE
Not specifying an InstrumentationKey for the Azure Application Insights sink throws an ArgumentException

### ISSUE THREAD

**Issue by fgheysels** [arcus-azure/arcus.observability#125]
When I configure SeriLog and want to make use of the ApplicationInsights sink, an ArgumentException is thrown when I pass in an empty instrumentation key.

Although I could understand the reasoning, I wonder if this is the behavior that we want.   When using Application Insights directly, one could also instantiate a TelemetryClient and pass in an empty instrumentationkey without an exception being thrown.
I think we should adhere to that behavior.

I have for instance a use case where I've an containerized API which is deployed in Azure, and the same API is also deployed on a boat.   Since the ship does not always have a connection to the Internet, I'm not logging to AppInsights in that case, so my configuration doesn't contain an instrumentation key.  In that case, an exception is thrown when the Serilog logger is being instantiated.

**Comment by tomkerkhove** [comment]
I'm not sure if I agree because you could also argue that you have to verify that you effectively need that sink or not. If we change this, how do we ensure that everything is good to go?

For example, maybe there is a bug where the key is not passed correctly while you assume that it's configured correctly but don't see telemetry? We prefer to fail fast rather than move on to help analysis.

**Comment by fgheysels** [comment]
I mostly agree with failing fast, but I also tend to be somewhat 'in line' with the behaviour of the existing Application Insights packages.

**Comment by tomkerkhove** [comment]
But how would you know it's because of the config key, bug in our code or in Arcus? Log the key? 😅

**Comment by tomkerkhove** [comment]
Could be as simple as this:
```csharp
var loggerConfig =  new LoggerConfiguration()
    .MinimumLevel.Debug();

if(string.IsNullOrEmpty(key) == false)
{
    loggerConfig.WriteTo.AzureApplicationInsights(key);
}

ILogger logger = loggerConfig.CreateLogger();
```

**Comment by fgheysels** [comment]
I wonder what should be done with this one.

I can agree with failing fast but I also feel that some similarity with the 'regular App Insights' functionality might be taken into consideration.  
It's up to you guys, I can live with failing fast as well.  Some extra plumbing is required by the user / programmer, but it is not insurmountable.

**Comment by tomkerkhove** [comment]
Frankly, I'd prefer to keep it as is to be stricter - I've never liked the SDK model as it can be very confusing to troubleshoot (I've been there).

Now I don't want to block you so we have two options:
- Update docs to include the sample (if need be)
- Provide an optional flag so that it just proceeds and doesn't validate (ie. `validateTelemetryKey: false`)

Does that make sense to you and/or what do you prefer?

**Comment by fgheysels** [comment]
I'm not in favor of the optional flag approach; rather add a sample to the documentation.

**Comment by tomkerkhove** [comment]
I'll update the docs!
