### ISSUE TITLE
Question - should we allow the possibility to provide exception during dependency failure tracking?

### ISSUE THREAD

**Issue by stijnmoreels** [arcus-azure/arcus.observability#149]
When we track a dependency together with a result flag (success/failure), should we allow an exception instance when there's a failure? It seems that there are cases where the exception can be the cause of a dependency failure and then it seems logic to include that, or should this be part of the telemetry context instead?

**Comment by tomkerkhove** [comment]
Can you provide an example of this?

**Comment by stijnmoreels** [comment]
Sometimes an exception is the reason why the dependency was unsuccessful. Currently, you can just pass along the success/failure flag but not extra info. You'll have to add yourself the telemetry data of the exception, which is commonly related to [this](https://github.com/microsoft/ApplicationInsights-dotnet/blob/develop/BASE/src/Microsoft.ApplicationInsights/DataContracts/ExceptionTelemetry.cs). So, I saw also that normally you have to track the dependency and the error separate, but not sure if that is needed. Maybe we can provide an overload where we pass the exception and the extracion of the information is done for us.

**Comment by tomkerkhove** [comment]
This is were correlation comes in I think - You'll be tracking a failed dependency and an exception separately and thanks to your correlation you'll be able to diagnose that.

I don't think we should do much on this front to be honest, because not everyone would want to have an additional exception being tracked because they already to it automatically for example.

**Comment by stijnmoreels** [comment]
Ah, ok, I'll close this.
