### ISSUE TITLE
Guidance/documentation on how to use WithCorrelationInfo

### ISSUE THREAD

**Issue by fgheysels** [arcus-azure/arcus.observability#178]
I've seen that the `WithCorrelationInfo` [method ](https://github.com/arcus-azure/arcus.observability/blob/1e75ba255da9d44451562afd7fbe60c78efe0879/src/Arcus.Observability.Telemetry.Serilog.Enrichers/Extensions/LoggerEnrichmentConfigurationExtensions.cs#L126)which uses (optional) parameters that have default values is now obsolete.

It would be nice if there is some guidance on how to use the method that is being referred to now.   What should be given as a value for the parameters ?

Also, related question:  why isn't the generic overload which relies on optional parameters marked as obsolete  ?

**Comment by stijnmoreels** [comment]
> Also, related question: why isn't the generic overload which relies on optional parameters marked as obsolete ?

There are two extensions marked as obsolete. One where the default `CorrelationInfo` is used and one where a custom `CorrelationImfo` can be used. The reason why they were both marked and not the others, is because they both used the default `ICorrelationInfoAccessor` internally but the user didn't have any 'hook' to retrieve this default instance because it wasn't registered in the `ISerbiceProvider`.
The two extensions that are refered to, will require only that single extra parameters, which is the `IServiceProvider` so we can retrieve such accessor instead of getting one ourselves internally. This way the user can set the correlation at any given time.

**Comment by stijnmoreels** [comment]
Maybe this question is more for in the discussions than in the issues, @tomkerkhove what do you think?

**Comment by tomkerkhove** [comment]
If it's something we have to improve in the docs -> Issue; if it's purely a question -> Discussion.

**Comment by stijnmoreels** [comment]
This is already covered in discussions and separate issues: we be simplified in next major. Closing for now.
