### ISSUE TITLE
Improve the LogSqlDependency method signature

### ISSUE THREAD

**Issue by fgheysels** [arcus-azure/arcus.observability#286]
The `LogSqlDependency` extension method on `ILogger` has a parameter which is called `tableName`.

This is a bit shortcoming as, when you want to log a dependency on SQL server, you execute (in most cases) a query that touches multiple tables.
This `tableName` parameter is used to build up the `dependencyName`:

![image](https://user-images.githubusercontent.com/3605786/152493532-a01f0a09-a8d8-455f-9969-c76f28b2302f.png)

It makes no sense to pass in a single tablename if you perform a SQL query that touches multiple tables, so it would be better if we:

- rename the `tableName` parameter to something more generic:  `sqlCommand`  or `sqlCommandInfo`
- Since that parameter can contain a lot more information, it should not be used to build up the `dependencyName`.  Only the database-name should be in the dependency name.
- The `sqlCommand` / `sqlCommandInfo` parameter can be logged as a contextual item / dimension
- The `sqlCommand`/ `sqlCommandInfo`  parameter should not be considered as mandatory, so we should not guard it.

See also this dicussion: https://github.com/arcus-azure/arcus.observability/discussions/265

**Comment by fgheysels** [comment]
I believe that, the `operationName` parameter becomes obsolete when we use a `sqlCommandInfo` parameter instead

**Comment by stijnmoreels** [comment]
We can indeed move from the `tableName` towards something else, bc, like you said, it doesn't make sense when the query spans multiple tables. But, I have reservations on an optional contextual property being part of the signature. Couldn't this then be something that the consumer choses to add or not instead of making this explicit in the signature? SQL may need some other interesting contextual information, but I think it would be 'overload' to try to add these to the signature or provide an 'info'-something to encompass all this. If this would be used as dependency data solely, then yeah, that could be useful. We will have to check if we can fluently move from this one to another one without breaking changes as the amount of parameters will stay the same and will have the same type.

**Comment by fgheysels** [comment]
Don't know  why this one is closed, as the tableName and operationName are still mandatory in this method.

**Comment by fgheysels** [comment]
Ah, it is just not released yet ?

**Comment by stijnmoreels** [comment]
> Ah, it is just not released yet ?

That's right. The other methods without the dependency ID aren't updated, though,  so maybe we should also create alternatives for those ones?
