### ISSUE TITLE
Make `dependencyName` in SQL dependency tracking more unique

### ISSUE THREAD

**Issue by stijnmoreels** [arcus-azure/arcus.observability#419]
**Is your feature request related to a problem? Please describe.**
In a previous release, we made sure that we could pass-in a pseudo SQL command because it is quite common to interact with multiple SQL tables in a realistic application (JOIN, multiple SELECT...).
Although, this change cased a more general `dependencyName` for SQL dependency tracking, which messed up the performance overview as all dependency tracking is now under the same `databaseName`.

**Describe the solution you'd like**
We should make sure that we again make the SQL dependency tracking more unique. We could do this by adding (for example) the pseudo SQL command to the `dependencyName`.

`<databaseName>/<sqlCommand`
`Orders/SELECT OrderId FROM Orders`

Discovered by @pim-simons .

**Comment by pim-simons** [comment]
Some more context, pre version 2.5.0 the performance logging looked like this (where red is the databasename and blue the tablename):
![image](https://user-images.githubusercontent.com/32359437/175889011-a24f3d53-2675-4ee9-bd89-09b582631243.png)

With version 2.5.0 I noticed this:
![image](https://user-images.githubusercontent.com/32359437/175889245-be7fbd3e-11e3-450b-98a4-929fbdfdec35.png)
And changed the logging to the new way of working where we do not specify a table name but include a pseudo SQL command.

Now the performance logging looks like this (where red is the databasename and green the servername):
![image](https://user-images.githubusercontent.com/32359437/175889596-e481afae-84bf-49f0-98ed-a8e0ca86ea69.png)

Instead of having a performance overview per table (or per pseudo SQL command) I now have all SQL logging as a single line in the performance logging and we lose some information on the performance of the specific commands.

**Comment by fgheysels** [comment]
My 2 cents:  can we change this so that the pseudo SQL Command is written as a custom dimension on the dependency instead ?
The dependency name should then be the databasename + a functional description of the operation ?
