### ISSUE TITLE
ApplicationInsights sink doesn't work if you explicitly install serilog.sinks.ApplicationInsights v4

### ISSUE THREAD

**Issue by sandernaert** [arcus-azure/arcus.observability#469]
**Describe the bug**

Arcus.Observability.Telemetry.Serilog.Sinks.ApplicationInsights doesn't work with Serilog.Sinks.ApplicationInsights

System.TypeLoadException: Could not load type 'Serilog.Sinks.ApplicationInsights.Sinks.ApplicationInsights.TelemetryConverters.TelemetryConverterBase' from assembly 'Serilog.Sinks.ApplicationInsights, Version=4.0.0.0

**To Reproduce**
Just install latest package of the arcus package and install serilog.sinks.applicationinsights 4.0

**Expected behavior**
Things to work

**Additional context**
Serilog fixed the namespaces to be more logical in v4.0
https://github.com/serilog-contrib/serilog-sinks-applicationinsights/commit/8e4e26a8fdfa12da6ed15afcc94889e5f399ff97

**Comment by stijnmoreels** [comment]
Hey, thx for the issue.
We could update the `Serilog.Sinks.ApplicationInsights` package in the `Arcus.Observability.Telemetry.Serilog.Sinks.ApplicationInsights` so that the fixed namespaces are present.

**Comment by fgheysels** [comment]
Just for my understanding:
- You've installed the latest version Arcus.Observability.Serilog.Sinks.applicaitonInsights (which has a dependency on Serilog.Sinks.ApplicationInsights v3.1.0)
- You've additionally installed Serilog.Sinks.ApplicationInsights v4.0 so that an issue with Serilog is fixed

Indeed @stijnmoreels , we can update the Serilog package in Arcus.
Of course, as is obvious from the versioning of the Serilog package, there might be breaking changes applicable to the Arcus component.

**Comment by stijnmoreels** [comment]
You want to take this up, @sandernaert ?

**Comment by sandernaert** [comment]
> versioning

Not exactly. I had a solution that already used Serilog.Sinks.ApplicationInsights v4.0, then I decided to use the Arcus library and noticed that it didn't work. I could solve it by just removing the serilog package.
